name: Bug report
description: Report a bug with the WordPress block editor or Gutenberg plugin
body:

    - type: markdown
      attributes:
          value: |
              __Thanks for taking the time to fill out this bug report!__

    - type: textarea
      attributes:
          label: Description
          description: Please write a brief description of the bug, including what you expect to happen and what is currently happening.
          placeholder: |
              Feature '...' is not working properly. I expect '...' to happen, but '...' happens instead
      validations:
          required: true

    - type: textarea
      attributes:
          label: Step-by-step reproduction instructions
          placeholder: |
              1. Go to '...'
              2. Click on '...'
              3. Scroll down to '...'
      validations:
          required: true

    - type: textarea
      attributes:
          label: Screenshots, screen recording, code snippet
          description: |
              If possible, please upload a screenshot or screen recording which demonstrates the bug.
      validations:
          required: false

    - type: dropdown
      id: existing
      attributes:
          label: Checked for existing bug reports?
          description: Please confirm that you searched for existing bug reports in https://github.com/Automattic/pocket-casts-android/issues before opening this issue.
          multiple: true
          options:
              - 'Yes'
              - 'No'
      validations:
          required: true

    - type: dropdown
      id: existing
      attributes:
          label: Checked for existing bug reports?
          description: Please confirm that you searched for existing bug reports in https://github.com/Automattic/pocket-casts-android/issues before opening this issue.
          multiple: true
          options:
              - 'I have checked for existing bug reports and did not find any.'
      validations:
          required: true


    - type: input
      attributes:
          label: Device
          placeholder: e.g. Google Pixel 6
      validations:
          required: true

    - type: input
      attributes:
          label: Operating system
          placeholder: e.g. Android 12
      validations:
          required: true

    - type: input
      attributes:
          label: Pocket Casts app version
          placeholder: e.g. 7.19.0
      validations:
          required: true